version: '3.3'

services:
    redis:
      image: redis:4.0.5-alpine
      command: ["redis-server", "--appendonly", "yes"]
      hostname: redis
      networks:
        - redis-net
      volumes:
        - redis-data:/data
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"

